name = "bit-vpn-converter"
compatibility_date = "2024-04-26"

# 添加环境变量配置
[vars]
NODE_ENV = "production"

[build]
command = "pnpm build"

[site]
bucket = ".vercel/output/static"
pages_build_output_dir = "out"

# 添加静态资产配置
[assets]
browser_TTL = 86400
serve_single_page_app = true