name = "bit-vpn-converter"
compatibility_date = "2024-04-26"
pages_build_output_dir = ".vercel/output"

# [vars]
# build_command = "pnpm run build"

# NODE_ENV = "production"
# 
# [build]
# command = "pnpm build"
# 
# [site]
# bucket = ".vercel/output/static"