name = "bit-vpn-converter"
compatibility_date = "2024-04-26"
pages_build_output_dir = "out"

# [vars]
# NODE_ENV = "production"
# 
# [build]
# command = "pnpm build"
# 
# [site]
# bucket = ".vercel/output/static"